### ISSUE TITLE
Add config file for generator

### ISSUE THREAD

**Issue by MHHukiewitz** [aleph-im/anchor-ts-generator#17]
`<insert-name-here> generate -f <path-to-idl.json> -c <path-to-config-file.yaml>`

```yaml
config:
  indexedAccountTypes:
    - SbState
    - OracleAccountData
    - AggregatorAccountData
```

Add config file functionality to CLI.
